[package]
name = "complier-dev"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
koopa = "0.0.8"
lalrpop-util = { version = "0.19.7", features = ["lexer"] }

[[bin]]
name = "complier"
path = "src/main.rs"